services:
  postgres:
    image: postgres:16-alpine
    container_name: contacts-postgres
    environment:
      POSTGRES_DB: ContactsArge24
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/backend/Contacts.Api/Dockerfile
    container_name: contacts-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5050
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ContactsArge24;Username=postgres;Password=postgres
      Database__ApplyMigrationsOnStartup: 'true'
    ports:
      - '5050:5050'
    depends_on:
      - postgres

  web:
    build:
      context: ./src/frontend/contacts-web
      dockerfile: Dockerfile
    container_name: contacts-web
    ports:
      - '4200:80'
    depends_on:
      - api

volumes:
  postgres-data:
